### ISSUE TITLE
Como recompensar nossos apoiadores e apoiadoras

### ISSUE THREAD

**Issue by woliveiras** [training-center/sponsors#2]
A algum tempo venho pensando em como recompensar melhor nossos apoiadores e apoiadoras, mas sem alguma ideia realmente interessante para nossa comunidade devido a demanda de trabalho manual intenso ou mesmo por falta de mão para ajudar nisso.

Vocês conseguem imaginar alguma maneira de recompensarmos as pessoas que nos apoiam financeiramente seja pelo [Apoia.se](https://apoia.se/training-center)?

**Comment by nicolastarzia** [comment]
@woliveiras,
Podemos fechar esta issue?

**Comment by woliveiras** [comment]
Podemos sim, @nicolastarzia
